src/Entity/Trick.php
<?php

namespace App\Entity;

use DateTime;
use App\Entity\Picture;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @UniqueEntity(
 * fields={"name"},
 * message="Une autre figure possède déjà ce nom."
 * )
 */
class Trick
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min=3,
     * max=25, 
     * minMessage="Le nom de la figure doit contenir plus de 3 caractères.", 
     * maxMessage="Le nom de la figure ne peut pas contenir plus de 25 caractères."
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     * min=5, 
     * minMessage="Le descriptif de la figure doit contenir plus de 5 caractères."
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="trick", cascade = {"persist"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $pictures;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="tricks")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Video", mappedBy="trick", cascade = {"persist"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $videos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->created_at = new DateTime();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function slugify($string, $delimiter = '-') 
    {   
        $stringClean = iconv('UTF-8', 'ASCII//TRANSLIT', $string);
        $stringClean = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $stringClean);
        $stringClean = strtolower($stringClean);
        $stringClean = preg_replace("/[\/_|+ -]+/", $delimiter, $stringClean);
        $stringClean = trim($stringClean, $delimiter);
        
        return $stringClean;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        $this->setSlug($this->name);

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
    
    public function setSlug($slug): self
    {
        $this->slug = $this->slugify($slug);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
   
    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrick($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getTrick() === $this) {
                $picture->setTrick(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->contains($video)) {
            $this->videos->removeElement($video);
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields={"username"},
 * message="Ce pseudo est déjà utilisé."
 * )
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cet email est déjà utilisé"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=2, max=50, 
     * minMessage="Votre pseudo doit contenir au moins 2 caractères.",
     * maxMessage="Votre pseudo doit contenir moins de 50 caractères.")
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, 
     * minMessage="Votre mot de passe doit contenir au moins 5 caractères.")
     */
    private $password;

     /**
     * @Assert\Length(min=5, 
     * minMessage="Votre mot de passe doit contenir au moins 5 caractères.")
     * @Assert\EqualTo(propertyPath="password", 
     * message="Les mots de passe saisies sont différents")
     */
    private $passwordVerification;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Cette adresse email n'est pas valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="user", orphanRemoval=true)
     */
    private $comments;

    public function __construct() 
    {
        $this->created_at = new DateTime();
        $this->comments = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function getPasswordVerification(): ?string
    {
        return $this->passwordVerification;
    }

    public function setPasswordVerification(string $passwordVerification): self
    {
        $this->passwordVerification = $passwordVerification;

        return $this;
    }
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function eraseCredentials()
    {
        
    }

    public function getSalt()
    {
        
    }
    
    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use App\Form\VideoType;
use App\Entity\Category;
use App\Form\PictureType;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class TrickType extends ApplicationType
{    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, $this->fieldsConfiguration('Veuillez saisir le nom de la figure.')
            )
            ->add('description', TextareaType::class, $this->fieldsConfiguration('Veuillez saisir un descriptif de la figure.')
            )
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name'
            ])
            ->add('pictures', CollectionType::class, [
                'entry_type' => PictureType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'allow_file_upload' => true,
                'required' => false,
                'entry_options' => ['label' => false], 
                'by_reference' => false
            ])
            ->add('videos', CollectionType::class, [
                'entry_type' => VideoType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'required' => false,
                'by_reference' => false,
                'entry_options' => ['label' => false],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
            'translation_domain' => 'trick-form'
        ]);
    }
}

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une figure{% endblock %}
{% form_theme form _self %}
{% block body %}
	<section class="edit-trick">
		<div class="edit-trick-title">
			<h1>Modification de la figure</h1>
			<h2>{{ trick.name }}</h2>
		</div>
		<div class="edit-trick-content">
			{% if trick.pictures is not empty %}
				<div class="edit-trick-content-picture">
					{% for picture in trick.pictures %}
						{% if loop.first %}
							<figure class="edit-trick-content-picture-featured">
								<figcaption>
									{{ picture.caption }}
								</figcaption>
								<img src="{{ asset('uploads/pictures/' ~ picture.path) }}">
								<div class="edit-trick-content-picture-featured-icon">
									<a href="" class="js-modal-picture fas fa-pencil-alt"></a>
									<a class="btn-delete-picture fas fa-trash-alt" href=" " onclick="return confirm('Etes-vous sûr ?');"></a>
								</div>
							</figure>
						{% endif %}
					{% endfor %}
				</div>
			{% endif %}
			<div class="edit-trick-content-more">
				<input type="checkbox" hidden class="edit-trick-content-more-state" id="read-more">
				<div class="edit-trick-content-more-target">
					{{ form_start(form, { "attr": { "class": "edit-trick-content-form"} }) }}
					<div class="edit-trick-content-picture-title">
						<h2>Photos</h2>
					</div>
					<div class="edit-trick-content-picture-thumbnail">
						{% for picture in trick.pictures %}
							{% if not loop.first %}
								<figure class="edit-trick-content-picture-thumbnail-figure">
									<figcaption>
										{{ picture.caption }}
									</figcaption>
									<img src="{{ asset('uploads/pictures/' ~ picture.path) }}">
									<div class="edit-trick-content-picture-thumbnail-figure-icon">
										<a href="" class="js-modal-picture fas fa-pencil-alt"></a>
										<a class="btn-delete-picture fas fa-trash-alt" href="" onclick="return confirm('Etes-vous sûr ?');"></a>
									</div>
								</figure>
							{% endif %}
						{% endfor %}
					</div>
					{{ form_row(form.pictures) }}
					{% if trick.videos is not empty %}
						<div class="edit-trick-content-video">
							<div class="edit-trick-content-video-title">
								<h2>Vidéos</h2>
							</div>
							<div class="edit-trick-content-video-thumbnail">
								{% for video in trick.videos %}
									<div class="edit-trick-content-video-thumbnail-card">
										<iframe width="200" height="150" src="{{ video.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
										<div class="edit-trick-content-video-thumbnail-card-icon">
											<a href="#" class="js-modal-video fas fa-pencil-alt"></a>
											<a class="btn-delete-video fas fa-trash-alt" href="" onclick="return confirm('Etes-vous sûr ?');"></a>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					{% endif %}
					{{ form_row(form.videos) }}
				</div>
				<label for="read-more" class="edit-trick-content-more-trigger_closed btn">Voir plus</label>
				<label for="read-more" class="edit-trick-content-more-trigger_opened btn">Voir Moins</label>
			</div>
			{{ form_row(form.name) }}
			{{ form_row(form.description) }}
			{{ form_row(form.category) }}
			<button type="submit" class="btn">Valider</button>
			{{ form_end(form) }}
			<div class="edit-trick-content-details">
				<ul class="edit-trick-content-details-list">
					<li>Date de création :
						{{ trick.createdAt|date("d/m/Y") }}</li>
					<li>Date de modification :
						{{ trick.updatedAt|date("d/m/Y")}}</li>
				</ul>
			</div>
		</div>
	</div>
</section>
{% endblock %}
{% block form_row %}
<div class="edit-trick-content-form-row">
	{{ form_label(form) }}
	{{ form_widget(form) }}
	<div class="edit-trick-content-form-error">
		{{ form_errors(form) }}
	</div>
</div>
{% endblock %}
{% block _trick_pictures_row %}
{{ form_widget(form) }}
<button type="button" class="btn-add-picture" id="add_picture">Ajouter une autre photo</button>
{% endblock %}
{% block _trick_pictures_entry_widget %}
<div class="modal-none">
	<div class="edit-trick-content-form-entry">
		{{ form_label(form.file)}}
		{{ form_widget(form.file)}}
		<div class="edit-trick-content-form-error">
			{{ form_errors(form.file) }}
		</div>
	</div>
	<div class="edit-trick-content-form-entry">
		{{ form_label(form.caption)}}
		{{ form_widget(form.caption)}}
		<div class="edit-trick-content-form-error">
			{{ form_errors(form.caption) }}
		</div>
	</div>
	<button type="button" class="btn-delete-picture fas fa-trash-alt"></button>
</div>
{% endblock %}
{% block _trick_videos_row %}
{{ form_widget(form) }}
<button type="button" class="btn-add-video" id="add_video">Ajouter une autre vidéo</button>{% endblock %}{% block _trick_videos_entry_widget %}
<div class="modal-none">
	<div class="edit-trick-content-form-entry">
		{{ form_label(form.url) }}
		{{ form_widget(form.url) }}
		<div class="edit-trick-content-form-error">
			{{ form_errors(form.url) }}
		</div>
	</div>
	<div class="edit-trick-content-form-entry">
		{{ form_label(form.name) }}
		{{ form_widget(form.name) }}
		<div class="edit-trick-content-form-error">
			{{ form_errors(form.name) }}
		</div>
	</div>
	<button type="button" class="btn-delete-video fas fa-trash-alt"></button>
</div>
{% endblock %}
{% block javascripts %}{{ encore_entry_script_tags('js/edit-trick') }}{% endblock %}

templates/trick/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle figure{% endblock %}
{% form_theme form _self %}
{% block body %}
	<section class="add-trick">
		<div class="add-trick-title">
			<h1>Ajouter une nouvelle figure</h1>
		</div>
		{{ form_start(form, { 'attr': {'class': 'add-trick-form'} }) }}
		{{ form_row(form.name) }}
		{{ form_row(form.description) }}
		{{ form_row(form.category) }}
		{{ form_row(form.pictures) }}
		{{ form_row(form.videos) }}
		<button type="submit" class="btn btn-form">Valider</button>
		{{ form_end(form) }}
	</section>
{% endblock %}
{% block form_row %}
	<div class="add-trick-form-row">
		{{ form_label(form) }}
		{{ form_widget(form) }}
		<div class="add-trick-form-error">
			{{ form_errors(form) }}
		</div>
	</div>
{% endblock %}
{% block _trick_pictures_row %}
	<h3>Ajouter des photos</h3>
	{{ form_widget(form) }}
	<button type="button" class="btn-add-picture" id="add_picture">Ajouter une autre photo</button>
{% endblock %}
{% block _trick_pictures_entry_widget %}
	<div class="add-trick-form-entry">
		{{ form_label(form.file)}}
		{{ form_widget(form.file)}}
		<div class="add-trick-form-error">
			{{ form_errors(form.file) }}
		</div>
	</div>
	<div class="add-trick-form-entry">
		{{ form_label(form.caption)}}
		{{ form_widget(form.caption)}}
		<div class="add-trick-form-error">
			{{ form_errors(form.caption) }}
		</div>
	</div>
	<button type="button" class="btn-delete-picture fas fa-trash-alt"></button>
{% endblock %}
{% block _trick_videos_row %}
	<h3>Ajouter des vidéos</h3>
	{{ form_widget(form) }}
	<button type="button" class="btn-add-video" id="add_video">Ajouter une autre vidéo</button>
{% endblock %}
{% block _trick_videos_entry_widget %}
	<div class="add-trick-form-entry">
		{{ form_label(form.url) }}
		{{ form_widget(form.url) }}
		<div class="add-trick-form-error">
			{{ form_errors(form.url) }}
		</div>
	</div>
	<div class="add-trick-form-entry">
		{{ form_label(form.name) }}
		{{ form_widget(form.name) }}
		<div class="add-trick-form-error">
			{{ form_errors(form.name) }}
		</div>
	</div>
	<button type="button" class="btn-delete-video fas fa-trash-alt"></button>
{% endblock %}
{% block javascripts %}{{ encore_entry_script_tags('js/add-trick') }}{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.name }}{% endblock %}

{% block body %}
	<section class="trick">
		{% set edit_url = path('trick_edit', {'slug':trick.slug}) %}
		{% set delete_url = path('trick_delete', {'slug':trick.slug}) %}
		<div class="trick-title">
			<h1>{{ trick.name }}</h1>
			{% if app.user %}
				<div class="trick-title-icon">
					<a class="fas fa-pencil-alt" href="{{ edit_url }}"></a>
					<a href="{{ delete_url }}" class="fas fa-trash-alt" onclick="return confirm('Etes-vous sûr de vouloir supprimer cette figure ?');"></a>
				</div>
			{% endif %}
		</div>
		<div class="trick-content">
			
				{% if trick.pictures is defined %}
				{% for picture in trick.pictures %}
					{% if loop.first %}
						<div class="trick-content-img">
							<figure class="trick-content-img-figure">
								<img src="{{ asset('uploads/pictures/' ~ picture.path) }}">
							</figure>
						</div>
					{% endif %}
				{% else %}
					<div class="trick-content-img">
						<figure class="tricks-content-card-img-figure">
							<a><img src="{{ asset('uploads/pictures/default-picture.png') }}"></a>
						</figure>
					</div>
						{% endfor %}
				{% endif %}
		
			<div class="trick-content-more">
				<input type="checkbox" hidden class="trick-content-more-state" id="read-more">
				<div class="trick-content-more-target">
					<div class="trick-content-title-img">
						<h3>Photos</h3>
					</div>
					<div class="trick-content-thumbnail">
						{% for picture in trick.pictures %}
							{% if not loop.first %}
								<figure class="trick-content-thumbnail-figure">
									<img src="{{ asset('uploads/pictures/' ~ picture.path) }}">
								</figure>
							{% endif %}
						{% endfor %}
					</div>
					<div class="trick-content-title-videos">
						<h3>Vidéos</h3>
					</div>
					<div class="trick-content-videos">
						{% for video in trick.videos %}
							<iframe src="{{ video.url }}" width="50%" frameborder="100" width="1920" height="1080" allowfullscreen></iframe>
						{% endfor %}
					</div>
				</div>
				<label for="read-more" class="trick-content-more-trigger_closed btn">Voir plus</label>
				<label for="read-more" class="trick-content-more-trigger_opened btn">Voir Moins</label>
			</div>
			<div class="trick-content-description">
				<p>{{ trick.description|nl2br }}</p>
			</div>
			<div class="trick-content-details">
				<ul class="trick-content-details-list">
					<li>Date de création :
						{{ trick.createdAt|date("d/m/Y") }}</li>
					{% if trick.updatedAt is not empty %}
						<li>Date de modification :
							{{ trick.updatedAt|date("d/m/Y")}}</li>
					{% endif %}
					<li>Catégorie :
						{{ trick.category.name }}</li>
				</ul>
			</div>
		</div>
	</section>
	<section class="trick-comment" id="comment">
		<div class="trick-comment-title">
			<h2>Commentaires</h2>
		</div>
		{% for comment in paginator.data %}
			<div class="trick-comment-content">
				<div class="trick-comment-content-user">
					<img class="trick-comment-profile-picture" src="{{ asset('uploads/profilePictures/'~ comment.user.profilePicture) }}">
					<h3>{{ comment.user.username }}</h3>
				</div>
				<div class="trick-comment-content-text">
					<h4>Le
						{{ comment.createdAt|date("d/m/Y \\à H:i:s","Europe/Paris") }}</h4>
					<p>{{ comment.content }}</p>
				</div>
				<hr>
			</div>
		{% else %}
			<div class="trick-comment-content">
				<p>Il n'y a pas encore de commentaire sur cette figure.</p>
			</div>
		{% endfor %}
		{% if app.user %}
			<div class="trick-comment-add">
				<div class="trick-comment-add-user">
					<img class="trick-comment-profile-picture" src="{{ asset('uploads/profilePictures/'~ user.profilePicture) }}">
					<h3>{{ user.username }}</h3>
				</div>
				<div class="trick-comment-add-form">
					{{ form_start(form) }}
					{{ form_row(form.content) }}
					<input type="submit" class="btn" value="Valider">
					{{ form_end(form) }}
				</div>
			</div>
		{% endif %}
		{% include 'shared/pagination.html.twig' with {'route': 'trick_show'} %}
	</section>
{% endblock %}
{% block form_row %}
	<div class="trick-comment-add-form-row">
		{{ form_widget(form) }}
		<div class="trick-comment-add-form-row-error">
			{{ form_errors(form) }}
		</div>
	</div>
{% endblock %}